### ISSUE TITLE
Documentation update for new DSL

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#22]
I tried to update the docs in the places I could think of. Where else do we need to update them?

See https://github.com/gradle/gradle/pull/417

**Comment by bigdaz** [comment]
We'll need to ensure the new DSL classes are included in the DSL reference, which means adding files to `subprojects/docs/src/docs/dsl`. You just document the methods and properties that you want included in the documentation.

We might also want to add more usage examples for the new DSL to `org.gradle.api.artifacts.DependencySubstitutions`, possibly to the individual methods. However, I'd hold off until we have a fuller discussion on a consistent approach for all resolution-rules DSLs.

There's the bigger picture of how the various dependency-resolution-rules fit into the broader model-rules infrastructure. I'd like to have Adam and/or Luke involved in these discussions.

Since this is now included as an open issue in the design spec, I'll close this issue.
